/** @format */

export enum userActionsTypes {
	GET_USER_SUCCESS = "GET_USER_SUCCESS",
	GET_USER_ERROR = "GET_USER_ERROR",
	GET_USER_LOADING = "GET_USER_LOADING",
	GET_USER_TOURS_SUCCESS = "GET_USER_TOURS_SUCCESS",
	GET_USER_TOURS_ERROR = "GET_USER_TOURS_ERROR",
}
